function [fitresult, gof] = createFit(x2, ch2)
%CREATEFIT(X2,CH2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x2
%      Y Output: ch2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Feb-2020 09:36:25


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x2, ch2 );

% Set up fittype and options.
ft = fittype( 'gauss4' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [238 6 5.59503594233948 224 85 4.35085878876586 215 46 3.00248149489365 58.9999999223569 60 446.472268628686];
opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'ch2 vs. x2', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'x2' );
% ylabel( 'ch2' );
% grid on


